version: "3.8"
services:
  elasticsearch:
    container_name: fineAnts_es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    platform: linux/x86_64
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_SECURITY}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - backend_net
  db:
    container_name: fineAnts_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command:
      - '--local-infile=1'
    networks:
      - backend_net
  redis:
    container_name: fineAnts_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_net
networks:
  backend_net:
